version: '3.1'
services:
  stats-server:
    build: stats-service/stats-service-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATABASE_URL=jdbc:postgresql://stats-db:5432/stats_DB
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DATABASE_URL=jdbc:postgresql://ewm-db:5432/service_DB
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=iamroot

  ewm-db:
    image: postgres:14-alpine
    container_name: service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=service_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
